const DEFAULT_VERTICAL_KEY = 'food-service';

const baseProfiles = {
  'food-service': {
    key: 'food-service',
    label: 'Alimentación',
    baseVertical: 'FOOD_SERVICE',
    allowsWeight: true,
    hasSizeMatrix: false,
    requiresSerial: false,
    supportsVariants: true,
    defaultUnits: ['kg', 'g', 'unidad'],
    attributeSchema: [
      { key: 'origin', label: 'Origen', type: 'string', scope: 'product' },
      {
        key: 'storageCondition',
        label: 'Condición de almacenamiento',
        type: 'enum',
        options: ['ambiente', 'refrigerado', 'congelado'],
        scope: 'product',
      },
    ],
    inventory: {
      supportsLots: true,
      supportsAttributeMatrix: false,
      requiresSerialTracking: false,
      alerts: ['lowStock', 'nearExpiration'],
    },
    orderLine: {
      requireAttributesOnAdd: false,
      allowCustomPrice: true,
      notesPlaceholder: 'Notas para preparación o entrega',
    },
    placeholders: {
      productName: 'Ej: Arroz Blanco',
      brand: 'Ej: Diana',
      sku: 'Ej: ARR-BLANCO',
      barcode: 'Ej: 7591234567890',
      category: 'Ej: Bebidas',
      subcategory: 'Ej: Gaseosas',
      description: 'Descripción detallada del producto',
      variantName: 'Ej: 1kg',
      variantSku: 'Ej: ARR-BLANCO-1KG',
      search: 'Buscar por nombre, SKU o marca...',
      sellingUnitName: 'Ej: Kilogramos',
      sellingUnitAbbreviation: 'Ej: kg',
      sellingUnitConversion: 'Ej: 1000',
      sellingUnitPrice: 'Ej: 20.00',
      sellingUnitCost: 'Ej: 12.00',
      sellingUnitMinQty: 'Ej: 0.5',
      sellingUnitIncrement: 'Ej: 0.5',
      variantUnit: 'Ej: kg, unidad',
      variantAdditionalName: 'Ej: Presentación 2kg',
      variantAdditionalSku: 'Ej: ARR-BLANCO-2KG',
    },
  },
  'retail-fashion': {
    key: 'retail-fashion',
    label: 'Moda / Ropa',
    baseVertical: 'RETAIL',
    allowsWeight: false,
    hasSizeMatrix: true,
    requiresSerial: false,
    supportsVariants: true,
    defaultUnits: ['unidad'],
    attributeSchema: [
      {
        key: 'size',
        label: 'Talla',
        type: 'enum',
        options: [],
        scope: 'variant',
        required: true,
        ui: { widget: 'chip' },
      },
      {
        key: 'color',
        label: 'Color',
        type: 'string',
        scope: 'variant',
        ui: { widget: 'chip' },
      },
      {
        key: 'gender',
        label: 'Género',
        type: 'enum',
        options: ['F', 'M', 'Unisex'],
        scope: 'product',
      },
      { key: 'season', label: 'Temporada', type: 'string', scope: 'product' },
    ],
    inventory: {
      supportsLots: false,
      supportsAttributeMatrix: true,
      requiresSerialTracking: false,
      alerts: ['lowStock'],
    },
    orderLine: {
      requireAttributesOnAdd: true,
      notesPlaceholder: 'Instrucciones de empaque o personalización',
    },
    placeholders: {
      productName: 'Ej: Camisa Oversize Essential',
      brand: 'Ej: Savage',
      sku: 'Ej: SVG-TEE-001',
      barcode: 'Ej: 8401234567890',
      category: 'Ej: Camisas',
      subcategory: 'Ej: Casual',
      description: 'Describe la prenda y sus materiales',
      variantName: 'Ej: Talla M / Color Negro',
      variantSku: 'Ej: SVG-TEE-001-M-NEGRO',
      search: 'Buscar por producto o SKU…',
      sellingUnitName: 'Ej: Unidad',
      sellingUnitAbbreviation: 'Ej: u',
      sellingUnitConversion: 'Ej: 1',
      sellingUnitPrice: 'Ej: 45.00',
      sellingUnitCost: 'Ej: 18.00',
      sellingUnitMinQty: 'Ej: 1',
      sellingUnitIncrement: 'Ej: 1',
      variantUnit: 'Ej: unidad',
      variantAdditionalName: 'Ej: Talla L / Color Blanco',
      variantAdditionalSku: 'Ej: SVG-TEE-001-L-BLANCO',
    },
  },
  'retail-footwear': {
    key: 'retail-footwear',
    label: 'Calzado',
    baseVertical: 'RETAIL',
    allowsWeight: false,
    hasSizeMatrix: true,
    requiresSerial: false,
    supportsVariants: true,
    defaultUnits: ['par'],
    attributeSchema: [
      {
        key: 'size',
        label: 'Talla',
        type: 'enum',
        options: [],
        scope: 'variant',
        required: true,
      },
      {
        key: 'width',
        label: 'Ancho',
        type: 'enum',
        options: ['Normal', 'Ancho'],
        scope: 'variant',
      },
      { key: 'material', label: 'Material', type: 'string', scope: 'product' },
    ],
    inventory: {
      supportsLots: false,
      supportsAttributeMatrix: true,
      requiresSerialTracking: false,
      alerts: ['lowStock'],
    },
    orderLine: {
      requireAttributesOnAdd: true,
    },
    placeholders: {
      productName: 'Ej: Sneakers Urban Pro',
      brand: 'Ej: StepUp',
      sku: 'Ej: SUP-SNK-001',
      barcode: 'Ej: 7509876543210',
      category: 'Ej: Calzado Deportivo',
      subcategory: 'Ej: Running',
      description: 'Especifica materiales y tecnología del calzado',
      variantName: 'Ej: Talla 41 / Color Negro',
      variantSku: 'Ej: SUP-SNK-001-41-N',
      search: 'Buscar por modelo o SKU…',
      sellingUnitName: 'Ej: Par',
      sellingUnitAbbreviation: 'Ej: par',
      sellingUnitConversion: 'Ej: 1',
      sellingUnitPrice: 'Ej: 68.00',
      sellingUnitCost: 'Ej: 30.00',
      sellingUnitMinQty: 'Ej: 1',
      sellingUnitIncrement: 'Ej: 1',
      variantUnit: 'Ej: par',
      variantAdditionalName: 'Ej: Talla 42 / Color Azul',
      variantAdditionalSku: 'Ej: SUP-SNK-001-42-A',
    },
  },
  'retail-hardware': {
    key: 'retail-hardware',
    label: 'Ferretería',
    baseVertical: 'RETAIL',
    allowsWeight: false,
    hasSizeMatrix: false,
    requiresSerial: false,
    supportsVariants: true,
    defaultUnits: ['unidad', 'pack'],
    attributeSchema: [
      {
        key: 'dimensions',
        label: 'Dimensiones',
        type: 'dimension',
        scope: 'product',
      },
      { key: 'gauge', label: 'Calibre', type: 'string', scope: 'variant' },
      {
        key: 'compatibility',
        label: 'Compatibilidad',
        type: 'string',
        scope: 'product',
        ui: { widget: 'textarea' },
      },
    ],
    inventory: {
      supportsLots: false,
      supportsAttributeMatrix: false,
      requiresSerialTracking: false,
      alerts: ['lowStock'],
    },
    orderLine: {
      requireAttributesOnAdd: false,
    },
    placeholders: {
      productName: 'Ej: Taladro Percutor 800W',
      brand: 'Ej: PowerFix',
      sku: 'Ej: PFX-DRL-800',
      barcode: 'Ej: 7703216549870',
      category: 'Ej: Herramientas Eléctricas',
      subcategory: 'Ej: Taladros',
      description: 'Resume potencia y aplicaciones recomendadas',
      variantName: 'Ej: Kit 110V',
      variantSku: 'Ej: PFX-DRL-800-K110',
      search: 'Buscar por herramienta o SKU…',
      sellingUnitName: 'Ej: Unidad',
      sellingUnitAbbreviation: 'Ej: u',
      sellingUnitConversion: 'Ej: 1',
      sellingUnitPrice: 'Ej: 95.00',
      sellingUnitCost: 'Ej: 60.00',
      sellingUnitMinQty: 'Ej: 1',
      sellingUnitIncrement: 'Ej: 1',
      variantUnit: 'Ej: unidad',
      variantAdditionalName: 'Ej: Kit 220V',
      variantAdditionalSku: 'Ej: PFX-DRL-800-K220',
    },
  },
  'retail-tech': {
    key: 'retail-tech',
    label: 'Tecnología',
    baseVertical: 'RETAIL',
    allowsWeight: false,
    hasSizeMatrix: false,
    requiresSerial: true,
    supportsVariants: true,
    defaultUnits: ['unidad'],
    attributeSchema: [
      {
        key: 'serial',
        label: 'Serial',
        type: 'string',
        scope: 'inventory',
        required: true,
      },
      {
        key: 'manufacturerSku',
        label: 'SKU Fabricante',
        type: 'string',
        scope: 'product',
      },
      {
        key: 'warranty',
        label: 'Garantía (meses)',
        type: 'number',
        scope: 'product',
      },
      {
        key: 'specs',
        label: 'Especificaciones',
        type: 'string',
        scope: 'product',
        ui: { widget: 'textarea' },
      },
    ],
    inventory: {
      supportsLots: false,
      supportsAttributeMatrix: false,
      requiresSerialTracking: true,
      alerts: ['lowStock', 'warranty'],
    },
    orderLine: {
      requireAttributesOnAdd: true,
      notesPlaceholder: 'Registrar notas sobre activación o configuración',
    },
    placeholders: {
      productName: 'Ej: Laptop Pro 14"',
      brand: 'Ej: Quantix',
      sku: 'Ej: QTX-LTP-14',
      barcode: 'Ej: 7701122334455',
      category: 'Ej: Computadoras',
      subcategory: 'Ej: Portátiles',
      description: 'Incluye procesador, RAM y almacenamiento',
      variantName: 'Ej: 16GB RAM / 512GB SSD',
      variantSku: 'Ej: QTX-LTP-14-16-512',
      search: 'Buscar por dispositivo o SKU…',
      sellingUnitName: 'Ej: Unidad',
      sellingUnitAbbreviation: 'Ej: u',
      sellingUnitConversion: 'Ej: 1',
      sellingUnitPrice: 'Ej: 1,299.00',
      sellingUnitCost: 'Ej: 890.00',
      sellingUnitMinQty: 'Ej: 1',
      sellingUnitIncrement: 'Ej: 1',
      variantUnit: 'Ej: unidad',
      variantAdditionalName: 'Ej: 32GB RAM / 1TB SSD',
      variantAdditionalSku: 'Ej: QTX-LTP-14-32-1T',
    },
  },
  'retail-toys': {
    key: 'retail-toys',
    label: 'Juguetería',
    baseVertical: 'RETAIL',
    allowsWeight: false,
    hasSizeMatrix: false,
    requiresSerial: false,
    supportsVariants: true,
    defaultUnits: ['unidad'],
    attributeSchema: [
      {
        key: 'ageRange',
        label: 'Rango de edad',
        type: 'range',
        scope: 'product',
        required: true,
      },
      {
        key: 'license',
        label: 'Licencia/Franquicia',
        type: 'string',
        scope: 'product',
      },
      {
        key: 'batteryType',
        label: 'Tipo de batería',
        type: 'enum',
        options: ['AA', 'AAA', 'Recargable', 'No requiere'],
        scope: 'product',
      },
      {
        key: 'safetyNotes',
        label: 'Advertencias de seguridad',
        type: 'string',
        scope: 'product',
        ui: { widget: 'textarea' },
      },
    ],
    inventory: {
      supportsLots: false,
      supportsAttributeMatrix: false,
      requiresSerialTracking: false,
      alerts: ['lowStock', 'ageRange'],
    },
    orderLine: {
      requireAttributesOnAdd: false,
      notesPlaceholder: 'Notas para envoltura o armado',
    },
  },
};

const mergeProfile = (base, overrides = {}) => {
  if (!overrides || typeof overrides !== 'object') {
    return { ...base };
  }

  return {
    ...base,
    ...overrides,
    defaultUnits: overrides.defaultUnits || base.defaultUnits,
    attributeSchema: overrides.attributeSchema || base.attributeSchema,
    inventory: {
      ...base.inventory,
      ...(overrides.inventory || {}),
    },
    orderLine: {
      ...base.orderLine,
      ...(overrides.orderLine || {}),
    },
  };
};

export const getVerticalProfile = (key = DEFAULT_VERTICAL_KEY, overrides) => {
  const base = baseProfiles[key] || baseProfiles[DEFAULT_VERTICAL_KEY];
  return mergeProfile(base, overrides);
};

export const listVerticalProfiles = () =>
  Object.values(baseProfiles).map(({ key, label, baseVertical }) => ({
    key,
    label,
    baseVertical,
  }));

export { DEFAULT_VERTICAL_KEY };
