/** Column mappings for generic Spanish Excel files */

export const genericProductPreset: Record<string, string> = {
  "Código": "sku",
  "Codigo": "sku",
  "Nombre": "name",
  "Categoría": "category",
  "Categoria": "category",
  "Subcategoría": "subcategory",
  "Subcategoria": "subcategory",
  "Marca": "brand",
  "Descripción": "description",
  "Descripcion": "description",
  "Tipo": "productType",
  "Perecedero": "isPerishable",
  "IVA": "taxCategory",
  "Aplica IVA": "ivaApplicable",
  "Presentación": "variantName",
  "Presentacion": "variantName",
  "Código de Barras": "variantBarcode",
  "Codigo de Barras": "variantBarcode",
  "Unidad": "variantUnit",
  "Contenido": "variantUnitSize",
  "Precio": "variantBasePrice",
  "Precio de Venta": "variantBasePrice",
  "Costo": "variantCostPrice",
  "Precio de Costo": "variantCostPrice",
  "Precio Mayorista": "variantWholesalePrice",
  "Stock": "initialStock",
  "Existencia": "initialStock",
  "Stock Mínimo": "minimumStock",
  "Stock Minimo": "minimumStock",
  "Punto de Reorden": "reorderPoint",
};

export const genericCustomerPreset: Record<string, string> = {
  "Nombre": "name",
  "Razón Social": "name",
  "Razon Social": "name",
  "Tipo": "customerType",
  "Correo": "email",
  "Email": "email",
  "Teléfono": "phone",
  "Telefono": "phone",
  "RIF": "taxId",
  "Cédula": "taxId",
  "Cedula": "taxId",
  "Tipo RIF": "taxType",
  "Empresa": "companyName",
  "Dirección": "address",
  "Direccion": "address",
  "Ciudad": "city",
  "Estado": "state",
  "Notas": "notes",
  "Activo": "isActive",
};

export const genericSupplierPreset: Record<string, string> = {
  "Nombre": "name",
  "Razón Social": "name",
  "Razon Social": "name",
  "Tipo": "supplierType",
  "RIF": "rif",
  "Contacto": "contactName",
  "Teléfono": "contactPhone",
  "Telefono": "contactPhone",
  "Correo": "contactEmail",
  "Email": "contactEmail",
  "Dirección": "address",
  "Direccion": "address",
  "Ciudad": "city",
  "Estado": "state",
  "Condición de Pago": "paymentTerms",
  "Condicion de Pago": "paymentTerms",
  "Notas": "notes",
  "Activo": "isActive",
};

export const genericInventoryPreset: Record<string, string> = {
  "SKU": "productSku",
  "Código": "productSku",
  "Codigo": "productSku",
  "Cantidad": "totalQuantity",
  "Stock": "totalQuantity",
  "Existencia": "totalQuantity",
  "Costo Promedio": "averageCostPrice",
  "Último Costo": "lastCostPrice",
  "Ultimo Costo": "lastCostPrice",
  "Almacén": "warehouseName",
  "Almacen": "warehouseName",
  "Motivo": "reason",
};
