/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ResponseError,
  ResponseSuccess,
} from '../models/index';
import {
    ResponseErrorFromJSON,
    ResponseErrorToJSON,
    ResponseSuccessFromJSON,
    ResponseSuccessToJSON,
} from '../models/index';

export interface BlacklistAddRequest {
    contactID: string;
}

export interface BlacklistRemoveRequest {
    contactID: string;
}

/**
 * 
 */
export class BlacklistApi extends runtime.BaseAPI {

    /**
     * Through this method, it is possible to add the contact on the disallowed list (blacklist). This will restrict the specified numbers to certain interactions with your account
     * Add contact to blacklist
     */
    async blacklistAddRaw(requestParameters: BlacklistAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseSuccess>> {
        if (requestParameters['contactID'] == null) {
            throw new runtime.RequiredError(
                'contactID',
                'Required parameter "contactID" was null or undefined when calling blacklistAdd().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // tokenAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/blacklist/{ContactID}`.replace(`{${"ContactID"}}`, encodeURIComponent(String(requestParameters['contactID']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseSuccessFromJSON(jsonValue));
    }

    /**
     * Through this method, it is possible to add the contact on the disallowed list (blacklist). This will restrict the specified numbers to certain interactions with your account
     * Add contact to blacklist
     */
    async blacklistAdd(requestParameters: BlacklistAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseSuccess> {
        const response = await this.blacklistAddRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Through this method, it is possible to remove the contact on the disallowed list (blacklist)
     * Remove contact from blacklist
     */
    async blacklistRemoveRaw(requestParameters: BlacklistRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseSuccess>> {
        if (requestParameters['contactID'] == null) {
            throw new runtime.RequiredError(
                'contactID',
                'Required parameter "contactID" was null or undefined when calling blacklistRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // tokenAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/blacklist/{ContactID}`.replace(`{${"ContactID"}}`, encodeURIComponent(String(requestParameters['contactID']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseSuccessFromJSON(jsonValue));
    }

    /**
     * Through this method, it is possible to remove the contact on the disallowed list (blacklist)
     * Remove contact from blacklist
     */
    async blacklistRemove(requestParameters: BlacklistRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseSuccess> {
        const response = await this.blacklistRemoveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
