/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActionListSectionsInnerProductItemsInner
 */
export interface ActionListSectionsInnerProductItemsInner {
    /**
     * Catalog ID
     * @type {string}
     * @memberof ActionListSectionsInnerProductItemsInner
     */
    catalogId?: string;
    /**
     * Product ID
     * @type {string}
     * @memberof ActionListSectionsInnerProductItemsInner
     */
    productId?: string;
}

/**
 * Check if a given object implements the ActionListSectionsInnerProductItemsInner interface.
 */
export function instanceOfActionListSectionsInnerProductItemsInner(value: object): value is ActionListSectionsInnerProductItemsInner {
    return true;
}

export function ActionListSectionsInnerProductItemsInnerFromJSON(json: any): ActionListSectionsInnerProductItemsInner {
    return ActionListSectionsInnerProductItemsInnerFromJSONTyped(json, false);
}

export function ActionListSectionsInnerProductItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActionListSectionsInnerProductItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'catalogId': json['catalog_id'] == null ? undefined : json['catalog_id'],
        'productId': json['product_id'] == null ? undefined : json['product_id'],
    };
}

export function ActionListSectionsInnerProductItemsInnerToJSON(json: any): ActionListSectionsInnerProductItemsInner {
    return ActionListSectionsInnerProductItemsInnerToJSONTyped(json, false);
}

export function ActionListSectionsInnerProductItemsInnerToJSONTyped(value?: ActionListSectionsInnerProductItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'catalog_id': value['catalogId'],
        'product_id': value['productId'],
    };
}

