/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActionProduct
 */
export interface ActionProduct {
    /**
     * Catalog ID
     * @type {string}
     * @memberof ActionProduct
     */
    catalogId?: string;
    /**
     * Product ID
     * @type {string}
     * @memberof ActionProduct
     */
    productId?: string;
}

/**
 * Check if a given object implements the ActionProduct interface.
 */
export function instanceOfActionProduct(value: object): value is ActionProduct {
    return true;
}

export function ActionProductFromJSON(json: any): ActionProduct {
    return ActionProductFromJSONTyped(json, false);
}

export function ActionProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActionProduct {
    if (json == null) {
        return json;
    }
    return {
        
        'catalogId': json['catalog_id'] == null ? undefined : json['catalog_id'],
        'productId': json['product_id'] == null ? undefined : json['product_id'],
    };
}

export function ActionProductToJSON(json: any): ActionProduct {
    return ActionProductToJSONTyped(json, false);
}

export function ActionProductToJSONTyped(value?: ActionProduct | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'catalog_id': value['catalogId'],
        'product_id': value['productId'],
    };
}

