/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type AddLabelAssociationAssociationIDParameter
 * 
 * @export
 */
export type AddLabelAssociationAssociationIDParameter = string;

export function AddLabelAssociationAssociationIDParameterFromJSON(json: any): AddLabelAssociationAssociationIDParameter {
    return AddLabelAssociationAssociationIDParameterFromJSONTyped(json, false);
}

export function AddLabelAssociationAssociationIDParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddLabelAssociationAssociationIDParameter {
    return json;
}

export function AddLabelAssociationAssociationIDParameterToJSON(json: any): any {
    return AddLabelAssociationAssociationIDParameterToJSONTyped(json, false);
}

export function AddLabelAssociationAssociationIDParameterToJSONTyped(value?: AddLabelAssociationAssociationIDParameter | null, ignoreDiscriminator: boolean = false): any {
    return value;
}