/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArchiveChatRequest
 */
export interface ArchiveChatRequest {
    /**
     * Archive or unarchive chat
     * @type {boolean}
     * @memberof ArchiveChatRequest
     */
    archive?: boolean;
}

/**
 * Check if a given object implements the ArchiveChatRequest interface.
 */
export function instanceOfArchiveChatRequest(value: object): value is ArchiveChatRequest {
    return true;
}

export function ArchiveChatRequestFromJSON(json: any): ArchiveChatRequest {
    return ArchiveChatRequestFromJSONTyped(json, false);
}

export function ArchiveChatRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArchiveChatRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'archive': json['archive'] == null ? undefined : json['archive'],
    };
}

export function ArchiveChatRequestToJSON(json: any): ArchiveChatRequest {
    return ArchiveChatRequestToJSONTyped(json, false);
}

export function ArchiveChatRequestToJSONTyped(value?: ArchiveChatRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archive': value['archive'],
    };
}

