/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BusinessHours } from './BusinessHours';
import {
    BusinessHoursFromJSON,
    BusinessHoursFromJSONTyped,
    BusinessHoursToJSON,
    BusinessHoursToJSONTyped,
} from './BusinessHours';

/**
 * 
 * @export
 * @interface BusinessProfileCustomHours
 */
export interface BusinessProfileCustomHours {
    /**
     * Timezone identifier
     * @type {string}
     * @memberof BusinessProfileCustomHours
     */
    timeZone?: string;
    /**
     * Working hours configuration
     * @type {Array<BusinessHours>}
     * @memberof BusinessProfileCustomHours
     */
    config?: Array<BusinessHours>;
}

/**
 * Check if a given object implements the BusinessProfileCustomHours interface.
 */
export function instanceOfBusinessProfileCustomHours(value: object): value is BusinessProfileCustomHours {
    return true;
}

export function BusinessProfileCustomHoursFromJSON(json: any): BusinessProfileCustomHours {
    return BusinessProfileCustomHoursFromJSONTyped(json, false);
}

export function BusinessProfileCustomHoursFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessProfileCustomHours {
    if (json == null) {
        return json;
    }
    return {
        
        'timeZone': json['timeZone'] == null ? undefined : json['timeZone'],
        'config': json['config'] == null ? undefined : ((json['config'] as Array<any>).map(BusinessHoursFromJSON)),
    };
}

export function BusinessProfileCustomHoursToJSON(json: any): BusinessProfileCustomHours {
    return BusinessProfileCustomHoursToJSONTyped(json, false);
}

export function BusinessProfileCustomHoursToJSONTyped(value?: BusinessProfileCustomHours | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timeZone': value['timeZone'],
        'config': value['config'] == null ? undefined : ((value['config'] as Array<any>).map(BusinessHoursToJSON)),
    };
}

