/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BusinessProfileCustomHours } from './BusinessProfileCustomHours';
import {
    BusinessProfileCustomHoursFromJSON,
    BusinessProfileCustomHoursFromJSONTyped,
    BusinessProfileCustomHoursToJSON,
    BusinessProfileCustomHoursToJSONTyped,
} from './BusinessProfileCustomHours';

/**
 * 
 * @export
 * @interface BusinessProfile
 */
export interface BusinessProfile {
    /**
     * Address of the business
     * Maximum of 256 characters
     * @type {string}
     * @memberof BusinessProfile
     */
    address?: string;
    /**
     * Description of the business
     * Maximum of 256 characters
     * @type {string}
     * @memberof BusinessProfile
     */
    description?: string;
    /**
     * Email address to contact the business
     * Maximum of 128 characters
     * @type {string}
     * @memberof BusinessProfile
     */
    email?: string;
    /**
     * 
     * @type {BusinessProfileCustomHours}
     * @memberof BusinessProfile
     */
    hours?: BusinessProfileCustomHours;
    /**
     * URLs associated with business (e.g., website, Facebook page, Instagram)
     * Maximum of 2 websites with a maximum of 256 characters each
     * @type {Array<string>}
     * @memberof BusinessProfile
     */
    websites?: Array<string>;
    /**
     * User ID
     * @type {string}
     * @memberof BusinessProfile
     */
    id?: string;
}

/**
 * Check if a given object implements the BusinessProfile interface.
 */
export function instanceOfBusinessProfile(value: object): value is BusinessProfile {
    return true;
}

export function BusinessProfileFromJSON(json: any): BusinessProfile {
    return BusinessProfileFromJSONTyped(json, false);
}

export function BusinessProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : json['address'],
        'description': json['description'] == null ? undefined : json['description'],
        'email': json['email'] == null ? undefined : json['email'],
        'hours': json['hours'] == null ? undefined : BusinessProfileCustomHoursFromJSON(json['hours']),
        'websites': json['websites'] == null ? undefined : json['websites'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function BusinessProfileToJSON(json: any): BusinessProfile {
    return BusinessProfileToJSONTyped(json, false);
}

export function BusinessProfileToJSONTyped(value?: BusinessProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'description': value['description'],
        'email': value['email'],
        'hours': BusinessProfileCustomHoursToJSON(value['hours']),
        'websites': value['websites'],
        'id': value['id'],
    };
}

