/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Button } from './Button';
import {
    ButtonFromJSON,
    ButtonFromJSONTyped,
    ButtonToJSON,
    ButtonToJSONTyped,
} from './Button';

/**
 * 
 * @export
 * @interface ButtonList
 */
export interface ButtonList {
    /**
     * Buttons
     * @type {Array<Button>}
     * @memberof ButtonList
     */
    buttons?: Array<Button>;
}

/**
 * Check if a given object implements the ButtonList interface.
 */
export function instanceOfButtonList(value: object): value is ButtonList {
    return true;
}

export function ButtonListFromJSON(json: any): ButtonList {
    return ButtonListFromJSONTyped(json, false);
}

export function ButtonListFromJSONTyped(json: any, ignoreDiscriminator: boolean): ButtonList {
    if (json == null) {
        return json;
    }
    return {
        
        'buttons': json['buttons'] == null ? undefined : ((json['buttons'] as Array<any>).map(ButtonFromJSON)),
    };
}

export function ButtonListToJSON(json: any): ButtonList {
    return ButtonListToJSONTyped(json, false);
}

export function ButtonListToJSONTyped(value?: ButtonList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'buttons': value['buttons'] == null ? undefined : ((value['buttons'] as Array<any>).map(ButtonToJSON)),
    };
}

