/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Chat } from './Chat';
import {
    ChatFromJSON,
    ChatFromJSONTyped,
    ChatToJSON,
    ChatToJSONTyped,
} from './Chat';

/**
 * 
 * @export
 * @interface ChatsList
 */
export interface ChatsList {
    /**
     * Count of requested chats
     * @type {number}
     * @memberof ChatsList
     */
    count?: number;
    /**
     * Total number of returned chats
     * @type {number}
     * @memberof ChatsList
     */
    total?: number;
    /**
     * Offset of requested chats
     * @type {number}
     * @memberof ChatsList
     */
    offset?: number;
    /**
     * 
     * @type {Array<Chat>}
     * @memberof ChatsList
     */
    chats?: Array<Chat>;
}

/**
 * Check if a given object implements the ChatsList interface.
 */
export function instanceOfChatsList(value: object): value is ChatsList {
    return true;
}

export function ChatsListFromJSON(json: any): ChatsList {
    return ChatsListFromJSONTyped(json, false);
}

export function ChatsListFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatsList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'total': json['total'] == null ? undefined : json['total'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'chats': json['chats'] == null ? undefined : ((json['chats'] as Array<any>).map(ChatFromJSON)),
    };
}

export function ChatsListToJSON(json: any): ChatsList {
    return ChatsListToJSONTyped(json, false);
}

export function ChatsListToJSONTyped(value?: ChatsList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'total': value['total'],
        'offset': value['offset'],
        'chats': value['chats'] == null ? undefined : ((value['chats'] as Array<any>).map(ChatToJSON)),
    };
}

