/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateLabel
 */
export interface CreateLabel {
    /**
     * Label ID
     * @type {string}
     * @memberof CreateLabel
     */
    id: string;
    /**
     * Label name
     * @type {string}
     * @memberof CreateLabel
     */
    name: string;
    /**
     * Label color
     * @type {string}
     * @memberof CreateLabel
     */
    color: CreateLabelColorEnum;
}


/**
 * @export
 */
export const CreateLabelColorEnum = {
    Salmon: 'salmon',
    Lightskyblue: 'lightskyblue',
    Gold: 'gold',
    Plum: 'plum',
    Silver: 'silver',
    Mediumturquoise: 'mediumturquoise',
    Violet: 'violet',
    Goldenrod: 'goldenrod',
    Cornflowerblue: 'cornflowerblue',
    Greenyellow: 'greenyellow',
    Cyan: 'cyan',
    Lightpink: 'lightpink',
    Mediumaquamarine: 'mediumaquamarine',
    Orangered: 'orangered',
    Deepskyblue: 'deepskyblue',
    Limegreen: 'limegreen',
    Darkorange: 'darkorange',
    Lightsteelblue: 'lightsteelblue',
    Mediumpurple: 'mediumpurple',
    Rebeccapurple: 'rebeccapurple'
} as const;
export type CreateLabelColorEnum = typeof CreateLabelColorEnum[keyof typeof CreateLabelColorEnum];


/**
 * Check if a given object implements the CreateLabel interface.
 */
export function instanceOfCreateLabel(value: object): value is CreateLabel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('color' in value) || value['color'] === undefined) return false;
    return true;
}

export function CreateLabelFromJSON(json: any): CreateLabel {
    return CreateLabelFromJSONTyped(json, false);
}

export function CreateLabelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLabel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'color': json['color'],
    };
}

export function CreateLabelToJSON(json: any): CreateLabel {
    return CreateLabelToJSONTyped(json, false);
}

export function CreateLabelToJSONTyped(value?: CreateLabel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'color': value['color'],
    };
}

