/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCommunityRequest
 */
export interface CreateCommunityRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateCommunityRequest
     */
    subject: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCommunityRequest
     */
    description: string;
}

/**
 * Check if a given object implements the CreateCommunityRequest interface.
 */
export function instanceOfCreateCommunityRequest(value: object): value is CreateCommunityRequest {
    if (!('subject' in value) || value['subject'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function CreateCommunityRequestFromJSON(json: any): CreateCommunityRequest {
    return CreateCommunityRequestFromJSONTyped(json, false);
}

export function CreateCommunityRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCommunityRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'subject': json['subject'],
        'description': json['description'],
    };
}

export function CreateCommunityRequestToJSON(json: any): CreateCommunityRequest {
    return CreateCommunityRequestToJSONTyped(json, false);
}

export function CreateCommunityRequestToJSONTyped(value?: CreateCommunityRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subject': value['subject'],
        'description': value['description'],
    };
}

