/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type GetPresenceEntryIDParameter
 * 
 * @export
 */
export type GetPresenceEntryIDParameter = string;

export function GetPresenceEntryIDParameterFromJSON(json: any): GetPresenceEntryIDParameter {
    return GetPresenceEntryIDParameterFromJSONTyped(json, false);
}

export function GetPresenceEntryIDParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPresenceEntryIDParameter {
    return json;
}

export function GetPresenceEntryIDParameterToJSON(json: any): any {
    return GetPresenceEntryIDParameterToJSONTyped(json, false);
}

export function GetPresenceEntryIDParameterToJSONTyped(value?: GetPresenceEntryIDParameter | null, ignoreDiscriminator: boolean = false): any {
    return value;
}