/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupApplication
 */
export interface GroupApplication {
    /**
     * Chat ID
     * @type {string}
     * @memberof GroupApplication
     */
    chatId?: string;
    /**
     * Application request method
     * @type {string}
     * @memberof GroupApplication
     */
    requestMethod?: string;
    /**
     * Application creation time
     * @type {number}
     * @memberof GroupApplication
     */
    timestamp?: number;
}

/**
 * Check if a given object implements the GroupApplication interface.
 */
export function instanceOfGroupApplication(value: object): value is GroupApplication {
    return true;
}

export function GroupApplicationFromJSON(json: any): GroupApplication {
    return GroupApplicationFromJSONTyped(json, false);
}

export function GroupApplicationFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupApplication {
    if (json == null) {
        return json;
    }
    return {
        
        'chatId': json['chatId'] == null ? undefined : json['chatId'],
        'requestMethod': json['request_method'] == null ? undefined : json['request_method'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function GroupApplicationToJSON(json: any): GroupApplication {
    return GroupApplicationToJSONTyped(json, false);
}

export function GroupApplicationToJSONTyped(value?: GroupApplication | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chatId': value['chatId'],
        'request_method': value['requestMethod'],
        'timestamp': value['timestamp'],
    };
}

