/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListReply
 */
export interface ListReply {
    /**
     * Clicked list ID
     * @type {string}
     * @memberof ListReply
     */
    id?: string;
    /**
     * Clicked list title
     * @type {string}
     * @memberof ListReply
     */
    title?: string;
    /**
     * Clicked list description
     * @type {string}
     * @memberof ListReply
     */
    description?: string;
}

/**
 * Check if a given object implements the ListReply interface.
 */
export function instanceOfListReply(value: object): value is ListReply {
    return true;
}

export function ListReplyFromJSON(json: any): ListReply {
    return ListReplyFromJSONTyped(json, false);
}

export function ListReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListReply {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ListReplyToJSON(json: any): ListReply {
    return ListReplyToJSONTyped(json, false);
}

export function ListReplyToJSONTyped(value?: ListReply | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
    };
}

