/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Media message type
 * @export
 */
export const MediaMessageType = {
    Image: 'image',
    Video: 'video',
    Gif: 'gif',
    Audio: 'audio',
    Voice: 'voice',
    Document: 'document',
    Sticker: 'sticker'
} as const;
export type MediaMessageType = typeof MediaMessageType[keyof typeof MediaMessageType];


export function instanceOfMediaMessageType(value: any): boolean {
    for (const key in MediaMessageType) {
        if (Object.prototype.hasOwnProperty.call(MediaMessageType, key)) {
            if (MediaMessageType[key as keyof typeof MediaMessageType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MediaMessageTypeFromJSON(json: any): MediaMessageType {
    return MediaMessageTypeFromJSONTyped(json, false);
}

export function MediaMessageTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaMessageType {
    return json as MediaMessageType;
}

export function MediaMessageTypeToJSON(value?: MediaMessageType | null): any {
    return value as any;
}

export function MediaMessageTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): MediaMessageType {
    return value as MediaMessageType;
}

