/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageContextADSource
 */
export interface MessageContextADSource {
    /**
     * ID of the advertisement source
     * @type {string}
     * @memberof MessageContextADSource
     */
    id?: string;
    /**
     * Type of the advertisement source
     * @type {string}
     * @memberof MessageContextADSource
     */
    type?: string;
    /**
     * URL of the advertisement source
     * @type {string}
     * @memberof MessageContextADSource
     */
    url?: string;
}

/**
 * Check if a given object implements the MessageContextADSource interface.
 */
export function instanceOfMessageContextADSource(value: object): value is MessageContextADSource {
    return true;
}

export function MessageContextADSourceFromJSON(json: any): MessageContextADSource {
    return MessageContextADSourceFromJSONTyped(json, false);
}

export function MessageContextADSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageContextADSource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function MessageContextADSourceToJSON(json: any): MessageContextADSource {
    return MessageContextADSourceToJSONTyped(json, false);
}

export function MessageContextADSourceToJSONTyped(value?: MessageContextADSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'url': value['url'],
    };
}

