/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageContentSystem
 */
export interface MessageContentSystem {
    /**
     * Message body
     * @type {string}
     * @memberof MessageContentSystem
     */
    body?: string;
}

/**
 * Check if a given object implements the MessageContentSystem interface.
 */
export function instanceOfMessageContentSystem(value: object): value is MessageContentSystem {
    return true;
}

export function MessageContentSystemFromJSON(json: any): MessageContentSystem {
    return MessageContentSystemFromJSONTyped(json, false);
}

export function MessageContentSystemFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageContentSystem {
    if (json == null) {
        return json;
    }
    return {
        
        'body': json['body'] == null ? undefined : json['body'],
    };
}

export function MessageContentSystemToJSON(json: any): MessageContentSystem {
    return MessageContentSystemToJSONTyped(json, false);
}

export function MessageContentSystemToJSONTyped(value?: MessageContentSystem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'body': value['body'],
    };
}

