/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageContentProductItems
 */
export interface MessageContentProductItems {
    /**
     * Type of interactive
     * @type {string}
     * @memberof MessageContentProductItems
     */
    type?: MessageContentProductItemsTypeEnum;
}


/**
 * @export
 */
export const MessageContentProductItemsTypeEnum = {
    List: 'list',
    Buttons: 'buttons'
} as const;
export type MessageContentProductItemsTypeEnum = typeof MessageContentProductItemsTypeEnum[keyof typeof MessageContentProductItemsTypeEnum];


/**
 * Check if a given object implements the MessageContentProductItems interface.
 */
export function instanceOfMessageContentProductItems(value: object): value is MessageContentProductItems {
    return true;
}

export function MessageContentProductItemsFromJSON(json: any): MessageContentProductItems {
    return MessageContentProductItemsFromJSONTyped(json, false);
}

export function MessageContentProductItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageContentProductItems {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function MessageContentProductItemsToJSON(json: any): MessageContentProductItems {
    return MessageContentProductItemsToJSONTyped(json, false);
}

export function MessageContentProductItemsToJSONTyped(value?: MessageContentProductItems | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

