/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Body of interactive
 * @export
 * @interface MessagePropsInteractiveBody
 */
export interface MessagePropsInteractiveBody {
    /**
     * Text of body
     * @type {string}
     * @memberof MessagePropsInteractiveBody
     */
    text?: string;
}

/**
 * Check if a given object implements the MessagePropsInteractiveBody interface.
 */
export function instanceOfMessagePropsInteractiveBody(value: object): value is MessagePropsInteractiveBody {
    return true;
}

export function MessagePropsInteractiveBodyFromJSON(json: any): MessagePropsInteractiveBody {
    return MessagePropsInteractiveBodyFromJSONTyped(json, false);
}

export function MessagePropsInteractiveBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessagePropsInteractiveBody {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'] == null ? undefined : json['text'],
    };
}

export function MessagePropsInteractiveBodyToJSON(json: any): MessagePropsInteractiveBody {
    return MessagePropsInteractiveBodyToJSONTyped(json, false);
}

export function MessagePropsInteractiveBodyToJSONTyped(value?: MessagePropsInteractiveBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
    };
}

