/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Button } from './Button';
import {
    ButtonFromJSON,
    ButtonFromJSONTyped,
    ButtonToJSON,
    ButtonToJSONTyped,
} from './Button';

/**
 * 
 * @export
 * @interface MessageContentVideo
 */
export interface MessageContentVideo {
    /**
     * Media ID
     * @type {string}
     * @memberof MessageContentVideo
     */
    id: string;
    /**
     * Optional. Link to media
     * @type {string}
     * @memberof MessageContentVideo
     */
    link?: string;
    /**
     * Mime type of media
     * @type {string}
     * @memberof MessageContentVideo
     */
    mimeType: string;
    /**
     * File size in bytes
     * @type {number}
     * @memberof MessageContentVideo
     */
    fileSize: number;
    /**
     * Optional. File name
     * @type {string}
     * @memberof MessageContentVideo
     */
    fileName?: string;
    /**
     * Checksum
     * @type {string}
     * @memberof MessageContentVideo
     */
    sha256?: string;
    /**
     * Created at
     * @type {number}
     * @memberof MessageContentVideo
     */
    timestamp?: number;
    /**
     * Optional. Text caption under the media.
     * @type {string}
     * @memberof MessageContentVideo
     */
    caption?: string;
    /**
     * Optional. Base64 encoded preview of the media. In JPEG format.
     * @type {string}
     * @memberof MessageContentVideo
     */
    preview?: string;
    /**
     * Width of the media in pixels
     * @type {number}
     * @memberof MessageContentVideo
     */
    width?: number;
    /**
     * Height of the media in pixels
     * @type {number}
     * @memberof MessageContentVideo
     */
    height?: number;
    /**
     * 
     * @type {Array<Button>}
     * @memberof MessageContentVideo
     */
    buttons?: Array<Button>;
    /**
     * Is view once
     * @type {boolean}
     * @memberof MessageContentVideo
     */
    viewOnce?: boolean;
    /**
     * Optional. For video files, this field indicates the duration of the video file in seconds.
     * @type {number}
     * @memberof MessageContentVideo
     */
    seconds?: number;
    /**
     * Optional. If the media is a GIF, this field indicates whether the GIF should be played automatically when the message is received.
     * @type {boolean}
     * @memberof MessageContentVideo
     */
    autoplay?: boolean;
}

/**
 * Check if a given object implements the MessageContentVideo interface.
 */
export function instanceOfMessageContentVideo(value: object): value is MessageContentVideo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('mimeType' in value) || value['mimeType'] === undefined) return false;
    if (!('fileSize' in value) || value['fileSize'] === undefined) return false;
    return true;
}

export function MessageContentVideoFromJSON(json: any): MessageContentVideo {
    return MessageContentVideoFromJSONTyped(json, false);
}

export function MessageContentVideoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageContentVideo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'link': json['link'] == null ? undefined : json['link'],
        'mimeType': json['mime_type'],
        'fileSize': json['file_size'],
        'fileName': json['file_name'] == null ? undefined : json['file_name'],
        'sha256': json['sha256'] == null ? undefined : json['sha256'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'caption': json['caption'] == null ? undefined : json['caption'],
        'preview': json['preview'] == null ? undefined : json['preview'],
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
        'buttons': json['buttons'] == null ? undefined : ((json['buttons'] as Array<any>).map(ButtonFromJSON)),
        'viewOnce': json['view_once'] == null ? undefined : json['view_once'],
        'seconds': json['seconds'] == null ? undefined : json['seconds'],
        'autoplay': json['autoplay'] == null ? undefined : json['autoplay'],
    };
}

export function MessageContentVideoToJSON(json: any): MessageContentVideo {
    return MessageContentVideoToJSONTyped(json, false);
}

export function MessageContentVideoToJSONTyped(value?: MessageContentVideo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'link': value['link'],
        'mime_type': value['mimeType'],
        'file_size': value['fileSize'],
        'file_name': value['fileName'],
        'sha256': value['sha256'],
        'timestamp': value['timestamp'],
        'caption': value['caption'],
        'preview': value['preview'],
        'width': value['width'],
        'height': value['height'],
        'buttons': value['buttons'] == null ? undefined : ((value['buttons'] as Array<any>).map(ButtonToJSON)),
        'view_once': value['viewOnce'],
        'seconds': value['seconds'],
        'autoplay': value['autoplay'],
    };
}

