/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessagePropsSticker
 */
export interface MessagePropsSticker {
    /**
     * Width of the media in pixels
     * @type {number}
     * @memberof MessagePropsSticker
     */
    width?: number;
    /**
     * Height of the media in pixels
     * @type {number}
     * @memberof MessagePropsSticker
     */
    height?: number;
    /**
     * Optional. For stickers, this field indicates whether the sticker is animated.
     * @type {boolean}
     * @memberof MessagePropsSticker
     */
    animated?: boolean;
}

/**
 * Check if a given object implements the MessagePropsSticker interface.
 */
export function instanceOfMessagePropsSticker(value: object): value is MessagePropsSticker {
    return true;
}

export function MessagePropsStickerFromJSON(json: any): MessagePropsSticker {
    return MessagePropsStickerFromJSONTyped(json, false);
}

export function MessagePropsStickerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessagePropsSticker {
    if (json == null) {
        return json;
    }
    return {
        
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
        'animated': json['animated'] == null ? undefined : json['animated'],
    };
}

export function MessagePropsStickerToJSON(json: any): MessagePropsSticker {
    return MessagePropsStickerToJSONTyped(json, false);
}

export function MessagePropsStickerToJSONTyped(value?: MessagePropsSticker | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'width': value['width'],
        'height': value['height'],
        'animated': value['animated'],
    };
}

