/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageContentContact
 */
export interface MessageContentContact {
    /**
     * Name of contact
     * @type {string}
     * @memberof MessageContentContact
     */
    name?: string;
    /**
     * Vcard of contact
     * @type {string}
     * @memberof MessageContentContact
     */
    vcard?: string;
    /**
     * Is view once
     * @type {boolean}
     * @memberof MessageContentContact
     */
    viewOnce?: boolean;
}

/**
 * Check if a given object implements the MessageContentContact interface.
 */
export function instanceOfMessageContentContact(value: object): value is MessageContentContact {
    return true;
}

export function MessageContentContactFromJSON(json: any): MessageContentContact {
    return MessageContentContactFromJSONTyped(json, false);
}

export function MessageContentContactFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageContentContact {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'vcard': json['vcard'] == null ? undefined : json['vcard'],
        'viewOnce': json['view_once'] == null ? undefined : json['view_once'],
    };
}

export function MessageContentContactToJSON(json: any): MessageContentContact {
    return MessageContentContactToJSONTyped(json, false);
}

export function MessageContentContactToJSONTyped(value?: MessageContentContact | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'vcard': value['vcard'],
        'view_once': value['viewOnce'],
    };
}

