/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Message source
 * @export
 */
export const MessageSource = {
    Web: 'web',
    Mobile: 'mobile',
    Api: 'api',
    System: 'system',
    BusinessApi: 'business_api',
    Unknown: 'unknown'
} as const;
export type MessageSource = typeof MessageSource[keyof typeof MessageSource];


export function instanceOfMessageSource(value: any): boolean {
    for (const key in MessageSource) {
        if (Object.prototype.hasOwnProperty.call(MessageSource, key)) {
            if (MessageSource[key as keyof typeof MessageSource] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MessageSourceFromJSON(json: any): MessageSource {
    return MessageSourceFromJSONTyped(json, false);
}

export function MessageSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageSource {
    return json as MessageSource;
}

export function MessageSourceToJSON(value?: MessageSource | null): any {
    return value as any;
}

export function MessageSourceToJSONTyped(value: any, ignoreDiscriminator: boolean): MessageSource {
    return value as MessageSource;
}

