/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageContentAudio
 */
export interface MessageContentAudio {
    /**
     * Media ID
     * @type {string}
     * @memberof MessageContentAudio
     */
    id: string;
    /**
     * Optional. Link to media
     * @type {string}
     * @memberof MessageContentAudio
     */
    link?: string;
    /**
     * Mime type of media
     * @type {string}
     * @memberof MessageContentAudio
     */
    mimeType: string;
    /**
     * File size in bytes
     * @type {number}
     * @memberof MessageContentAudio
     */
    fileSize: number;
    /**
     * Optional. File name
     * @type {string}
     * @memberof MessageContentAudio
     */
    fileName?: string;
    /**
     * Checksum
     * @type {string}
     * @memberof MessageContentAudio
     */
    sha256?: string;
    /**
     * Created at
     * @type {number}
     * @memberof MessageContentAudio
     */
    timestamp?: number;
    /**
     * Optional. For audio files, this field indicates the duration of the audio file in seconds.
     * @type {number}
     * @memberof MessageContentAudio
     */
    seconds?: number;
    /**
     * Time in seconds to simulate recording voice
     * @type {number}
     * @memberof MessageContentAudio
     */
    recordingTime?: number;
    /**
     * Is view once
     * @type {boolean}
     * @memberof MessageContentAudio
     */
    viewOnce?: boolean;
}

/**
 * Check if a given object implements the MessageContentAudio interface.
 */
export function instanceOfMessageContentAudio(value: object): value is MessageContentAudio {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('mimeType' in value) || value['mimeType'] === undefined) return false;
    if (!('fileSize' in value) || value['fileSize'] === undefined) return false;
    return true;
}

export function MessageContentAudioFromJSON(json: any): MessageContentAudio {
    return MessageContentAudioFromJSONTyped(json, false);
}

export function MessageContentAudioFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageContentAudio {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'link': json['link'] == null ? undefined : json['link'],
        'mimeType': json['mime_type'],
        'fileSize': json['file_size'],
        'fileName': json['file_name'] == null ? undefined : json['file_name'],
        'sha256': json['sha256'] == null ? undefined : json['sha256'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'seconds': json['seconds'] == null ? undefined : json['seconds'],
        'recordingTime': json['recording_time'] == null ? undefined : json['recording_time'],
        'viewOnce': json['view_once'] == null ? undefined : json['view_once'],
    };
}

export function MessageContentAudioToJSON(json: any): MessageContentAudio {
    return MessageContentAudioToJSONTyped(json, false);
}

export function MessageContentAudioToJSONTyped(value?: MessageContentAudio | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'link': value['link'],
        'mime_type': value['mimeType'],
        'file_size': value['fileSize'],
        'file_name': value['fileName'],
        'sha256': value['sha256'],
        'timestamp': value['timestamp'],
        'seconds': value['seconds'],
        'recording_time': value['recordingTime'],
        'view_once': value['viewOnce'],
    };
}

