/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * If 'body' contains a link, this props can be used to create custom preview link
 * @export
 * @interface MessagePropsLinkPreview
 */
export interface MessagePropsLinkPreview {
    /**
     * Title of the link
     * @type {string}
     * @memberof MessagePropsLinkPreview
     */
    title: string;
    /**
     * Description of the link
     * @type {string}
     * @memberof MessagePropsLinkPreview
     */
    description?: string;
    /**
     * Canonical URL of the link (for example, if the link is shortened)
     * @type {string}
     * @memberof MessagePropsLinkPreview
     */
    canonical?: string;
    /**
     * Base64 encoded image for mini version link preview. In JPEG format
     * @type {string}
     * @memberof MessagePropsLinkPreview
     */
    preview?: string;
}

/**
 * Check if a given object implements the MessagePropsLinkPreview interface.
 */
export function instanceOfMessagePropsLinkPreview(value: object): value is MessagePropsLinkPreview {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function MessagePropsLinkPreviewFromJSON(json: any): MessagePropsLinkPreview {
    return MessagePropsLinkPreviewFromJSONTyped(json, false);
}

export function MessagePropsLinkPreviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessagePropsLinkPreview {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'canonical': json['canonical'] == null ? undefined : json['canonical'],
        'preview': json['preview'] == null ? undefined : json['preview'],
    };
}

export function MessagePropsLinkPreviewToJSON(json: any): MessagePropsLinkPreview {
    return MessagePropsLinkPreviewToJSONTyped(json, false);
}

export function MessagePropsLinkPreviewToJSONTyped(value?: MessagePropsLinkPreview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'canonical': value['canonical'],
        'preview': value['preview'],
    };
}

