/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * See the https://whapi.cloud/docs/whatsapp/api/errors for more information.
     * @type {number}
     * @memberof ModelError
     */
    code: number;
    /**
     * error message
     * @type {string}
     * @memberof ModelError
     */
    message: string;
    /**
     * error detail
     * @type {string}
     * @memberof ModelError
     */
    details?: string;
    /**
     * location for error detail
     * @type {string}
     * @memberof ModelError
     */
    href?: string;
    /**
     * support contact
     * @type {string}
     * @memberof ModelError
     */
    support?: string;
}

/**
 * Check if a given object implements the ModelError interface.
 */
export function instanceOfModelError(value: object): value is ModelError {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ModelErrorFromJSON(json: any): ModelError {
    return ModelErrorFromJSONTyped(json, false);
}

export function ModelErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
        'details': json['details'] == null ? undefined : json['details'],
        'href': json['href'] == null ? undefined : json['href'],
        'support': json['support'] == null ? undefined : json['support'],
    };
}

export function ModelErrorToJSON(json: any): ModelError {
    return ModelErrorToJSONTyped(json, false);
}

export function ModelErrorToJSONTyped(value?: ModelError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'details': value['details'],
        'href': value['href'],
        'support': value['support'],
    };
}

