/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Newsletter } from './Newsletter';
import {
    NewsletterFromJSON,
    NewsletterFromJSONTyped,
    NewsletterToJSON,
    NewsletterToJSONTyped,
} from './Newsletter';

/**
 * 
 * @export
 * @interface NewslettersList
 */
export interface NewslettersList {
    /**
     * Count of requested chats
     * @type {number}
     * @memberof NewslettersList
     */
    count?: number;
    /**
     * Total number of returned chats
     * @type {number}
     * @memberof NewslettersList
     */
    total?: number;
    /**
     * Offset of requested chats
     * @type {number}
     * @memberof NewslettersList
     */
    offset?: number;
    /**
     * 
     * @type {Array<Newsletter>}
     * @memberof NewslettersList
     */
    newsletters?: Array<Newsletter>;
}

/**
 * Check if a given object implements the NewslettersList interface.
 */
export function instanceOfNewslettersList(value: object): value is NewslettersList {
    return true;
}

export function NewslettersListFromJSON(json: any): NewslettersList {
    return NewslettersListFromJSONTyped(json, false);
}

export function NewslettersListFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewslettersList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'total': json['total'] == null ? undefined : json['total'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'newsletters': json['newsletters'] == null ? undefined : ((json['newsletters'] as Array<any>).map(NewsletterFromJSON)),
    };
}

export function NewslettersListToJSON(json: any): NewslettersList {
    return NewslettersListToJSONTyped(json, false);
}

export function NewslettersListToJSONTyped(value?: NewslettersList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'total': value['total'],
        'offset': value['offset'],
        'newsletters': value['newsletters'] == null ? undefined : ((value['newsletters'] as Array<any>).map(NewsletterToJSON)),
    };
}

