/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductItem } from './ProductItem';
import {
    ProductItemFromJSON,
    ProductItemFromJSONTyped,
    ProductItemToJSON,
    ProductItemToJSONTyped,
} from './ProductItem';

/**
 * 
 * @export
 * @interface OrderItems
 */
export interface OrderItems {
    /**
     * 
     * @type {Array<ProductItem>}
     * @memberof OrderItems
     */
    items?: Array<ProductItem>;
}

/**
 * Check if a given object implements the OrderItems interface.
 */
export function instanceOfOrderItems(value: object): value is OrderItems {
    return true;
}

export function OrderItemsFromJSON(json: any): OrderItems {
    return OrderItemsFromJSONTyped(json, false);
}

export function OrderItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderItems {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(ProductItemFromJSON)),
    };
}

export function OrderItemsToJSON(json: any): OrderItems {
    return OrderItemsToJSONTyped(json, false);
}

export function OrderItemsToJSONTyped(value?: OrderItems | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(ProductItemToJSON)),
    };
}

