/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GroupIconParametersMedia } from './GroupIconParametersMedia';
import {
    GroupIconParametersMediaFromJSON,
    GroupIconParametersMediaFromJSONTyped,
    GroupIconParametersMediaToJSON,
    GroupIconParametersMediaToJSONTyped,
} from './GroupIconParametersMedia';
import type { Currency } from './Currency';
import {
    CurrencyFromJSON,
    CurrencyFromJSONTyped,
    CurrencyToJSON,
    CurrencyToJSONTyped,
} from './Currency';

/**
 * 
 * @export
 * @interface ProductCreate
 */
export interface ProductCreate {
    /**
     * Product Retailer ID
     * @type {string}
     * @memberof ProductCreate
     */
    productRetailerId?: string;
    /**
     * 
     * @type {Currency}
     * @memberof ProductCreate
     */
    currency: Currency;
    /**
     * Product images urls
     * @type {Array<GroupIconParametersMedia>}
     * @memberof ProductCreate
     */
    images: Array<GroupIconParametersMedia>;
    /**
     * Product availability
     * @type {string}
     * @memberof ProductCreate
     */
    availability?: ProductCreateAvailabilityEnum;
    /**
     * Product name
     * @type {string}
     * @memberof ProductCreate
     */
    name: string;
    /**
     * Product url
     * @type {string}
     * @memberof ProductCreate
     */
    url?: string;
    /**
     * Product description
     * @type {string}
     * @memberof ProductCreate
     */
    description: string;
    /**
     * Product price
     * @type {number}
     * @memberof ProductCreate
     */
    price: number;
    /**
     * Product is hidden
     * @type {boolean}
     * @memberof ProductCreate
     */
    isHidden?: boolean;
}


/**
 * @export
 */
export const ProductCreateAvailabilityEnum = {
    InStock: 'in stock',
    OutOfStock: 'out of stock'
} as const;
export type ProductCreateAvailabilityEnum = typeof ProductCreateAvailabilityEnum[keyof typeof ProductCreateAvailabilityEnum];


/**
 * Check if a given object implements the ProductCreate interface.
 */
export function instanceOfProductCreate(value: object): value is ProductCreate {
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('images' in value) || value['images'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    return true;
}

export function ProductCreateFromJSON(json: any): ProductCreate {
    return ProductCreateFromJSONTyped(json, false);
}

export function ProductCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'productRetailerId': json['product_retailer_id'] == null ? undefined : json['product_retailer_id'],
        'currency': CurrencyFromJSON(json['currency']),
        'images': ((json['images'] as Array<any>).map(GroupIconParametersMediaFromJSON)),
        'availability': json['availability'] == null ? undefined : json['availability'],
        'name': json['name'],
        'url': json['url'] == null ? undefined : json['url'],
        'description': json['description'],
        'price': json['price'],
        'isHidden': json['is_hidden'] == null ? undefined : json['is_hidden'],
    };
}

export function ProductCreateToJSON(json: any): ProductCreate {
    return ProductCreateToJSONTyped(json, false);
}

export function ProductCreateToJSONTyped(value?: ProductCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'product_retailer_id': value['productRetailerId'],
        'currency': CurrencyToJSON(value['currency']),
        'images': ((value['images'] as Array<any>).map(GroupIconParametersMediaToJSON)),
        'availability': value['availability'],
        'name': value['name'],
        'url': value['url'],
        'description': value['description'],
        'price': value['price'],
        'is_hidden': value['isHidden'],
    };
}

