/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReactToMessage
 */
export interface ReactToMessage {
    /**
     * Reaction text
     * @type {string}
     * @memberof ReactToMessage
     */
    emoji: string;
}

/**
 * Check if a given object implements the ReactToMessage interface.
 */
export function instanceOfReactToMessage(value: object): value is ReactToMessage {
    if (!('emoji' in value) || value['emoji'] === undefined) return false;
    return true;
}

export function ReactToMessageFromJSON(json: any): ReactToMessage {
    return ReactToMessageFromJSONTyped(json, false);
}

export function ReactToMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReactToMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'emoji': json['emoji'],
    };
}

export function ReactToMessageToJSON(json: any): ReactToMessage {
    return ReactToMessageToJSONTyped(json, false);
}

export function ReactToMessageToJSONTyped(value?: ReactToMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'emoji': value['emoji'],
    };
}

