/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RejectCallRequest
 */
export interface RejectCallRequest {
    /**
     * Contact ID
     * @type {string}
     * @memberof RejectCallRequest
     */
    callFrom: string;
}

/**
 * Check if a given object implements the RejectCallRequest interface.
 */
export function instanceOfRejectCallRequest(value: object): value is RejectCallRequest {
    if (!('callFrom' in value) || value['callFrom'] === undefined) return false;
    return true;
}

export function RejectCallRequestFromJSON(json: any): RejectCallRequest {
    return RejectCallRequestFromJSONTyped(json, false);
}

export function RejectCallRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RejectCallRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'callFrom': json['callFrom'],
    };
}

export function RejectCallRequestToJSON(json: any): RejectCallRequest {
    return RejectCallRequestToJSONTyped(json, false);
}

export function RejectCallRequestToJSONTyped(value?: RejectCallRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'callFrom': value['callFrom'],
    };
}

