/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseError
 */
export interface ResponseError {
    /**
     * 
     * @type {Error}
     * @memberof ResponseError
     */
    error: Error;
}

/**
 * Check if a given object implements the ResponseError interface.
 */
export function instanceOfResponseError(value: object): value is ResponseError {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function ResponseErrorFromJSON(json: any): ResponseError {
    return ResponseErrorFromJSONTyped(json, false);
}

export function ResponseErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseError {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

export function ResponseErrorToJSON(json: any): ResponseError {
    return ResponseErrorToJSONTyped(json, false);
}

export function ResponseErrorToJSONTyped(value?: ResponseError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

