/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseListParticipants
 */
export interface ResponseListParticipants {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseListParticipants
     */
    success?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof ResponseListParticipants
     */
    failed?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ResponseListParticipants
     */
    processed?: Array<string>;
}

/**
 * Check if a given object implements the ResponseListParticipants interface.
 */
export function instanceOfResponseListParticipants(value: object): value is ResponseListParticipants {
    return true;
}

export function ResponseListParticipantsFromJSON(json: any): ResponseListParticipants {
    return ResponseListParticipantsFromJSONTyped(json, false);
}

export function ResponseListParticipantsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseListParticipants {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'failed': json['failed'] == null ? undefined : json['failed'],
        'processed': json['processed'] == null ? undefined : json['processed'],
    };
}

export function ResponseListParticipantsToJSON(json: any): ResponseListParticipants {
    return ResponseListParticipantsToJSONTyped(json, false);
}

export function ResponseListParticipantsToJSONTyped(value?: ResponseListParticipants | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'failed': value['failed'],
        'processed': value['processed'],
    };
}

