/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActionListSectionsInnerRowsInner } from './ActionListSectionsInnerRowsInner';
import {
    ActionListSectionsInnerRowsInnerFromJSON,
    ActionListSectionsInnerRowsInnerFromJSONTyped,
    ActionListSectionsInnerRowsInnerToJSON,
    ActionListSectionsInnerRowsInnerToJSONTyped,
} from './ActionListSectionsInnerRowsInner';

/**
 * 
 * @export
 * @interface SectionListListSectionsInner
 */
export interface SectionListListSectionsInner {
    /**
     * Title of the section
     * @type {string}
     * @memberof SectionListListSectionsInner
     */
    title?: string;
    /**
     * Rows of the section
     * @type {Array<ActionListSectionsInnerRowsInner>}
     * @memberof SectionListListSectionsInner
     */
    rows?: Array<ActionListSectionsInnerRowsInner>;
}

/**
 * Check if a given object implements the SectionListListSectionsInner interface.
 */
export function instanceOfSectionListListSectionsInner(value: object): value is SectionListListSectionsInner {
    return true;
}

export function SectionListListSectionsInnerFromJSON(json: any): SectionListListSectionsInner {
    return SectionListListSectionsInnerFromJSONTyped(json, false);
}

export function SectionListListSectionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SectionListListSectionsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'rows': json['rows'] == null ? undefined : ((json['rows'] as Array<any>).map(ActionListSectionsInnerRowsInnerFromJSON)),
    };
}

export function SectionListListSectionsInnerToJSON(json: any): SectionListListSectionsInner {
    return SectionListListSectionsInnerToJSONTyped(json, false);
}

export function SectionListListSectionsInnerToJSONTyped(value?: SectionListListSectionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'rows': value['rows'] == null ? undefined : ((value['rows'] as Array<any>).map(ActionListSectionsInnerRowsInnerToJSON)),
    };
}

