/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SectionListList } from './SectionListList';
import {
    SectionListListFromJSON,
    SectionListListFromJSONTyped,
    SectionListListToJSON,
    SectionListListToJSONTyped,
} from './SectionListList';

/**
 * 
 * @export
 * @interface SectionList
 */
export interface SectionList {
    /**
     * 
     * @type {SectionListList}
     * @memberof SectionList
     */
    list?: SectionListList;
}

/**
 * Check if a given object implements the SectionList interface.
 */
export function instanceOfSectionList(value: object): value is SectionList {
    return true;
}

export function SectionListFromJSON(json: any): SectionList {
    return SectionListFromJSONTyped(json, false);
}

export function SectionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): SectionList {
    if (json == null) {
        return json;
    }
    return {
        
        'list': json['list'] == null ? undefined : SectionListListFromJSON(json['list']),
    };
}

export function SectionListToJSON(json: any): SectionList {
    return SectionListToJSONTyped(json, false);
}

export function SectionListToJSONTyped(value?: SectionList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'list': SectionListListToJSON(value['list']),
    };
}

