/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SendMediaMedia } from './SendMediaMedia';
import {
    SendMediaMediaFromJSON,
    SendMediaMediaFromJSONTyped,
    SendMediaMediaToJSON,
    SendMediaMediaToJSONTyped,
} from './SendMediaMedia';

/**
 * 
 * @export
 * @interface SenderStoriesAudio
 */
export interface SenderStoriesAudio {
    /**
     * 
     * @type {SendMediaMedia}
     * @memberof SenderStoriesAudio
     */
    media: SendMediaMedia;
    /**
     * Mime type of media
     * @type {string}
     * @memberof SenderStoriesAudio
     */
    mimeType?: string;
    /**
     * Do not use our encoding
     * @type {boolean}
     * @memberof SenderStoriesAudio
     */
    noEncode?: boolean;
    /**
     * Do not use the cache in a request
     * @type {boolean}
     * @memberof SenderStoriesAudio
     */
    noCache?: boolean;
    /**
     * Optional. For audio files, this field indicates the duration of the audio file in seconds.
     * @type {number}
     * @memberof SenderStoriesAudio
     */
    seconds?: number;
    /**
     * Width of the media in pixels
     * @type {number}
     * @memberof SenderStoriesAudio
     */
    width?: number;
    /**
     * Height of the media in pixels
     * @type {number}
     * @memberof SenderStoriesAudio
     */
    height?: number;
    /**
     * List of contacts to send the story to
     * @type {Array<string>}
     * @memberof SenderStoriesAudio
     */
    contacts?: Array<string>;
    /**
     * List of contacts to exclude
     * @type {Array<string>}
     * @memberof SenderStoriesAudio
     */
    excludeContacts?: Array<string>;
    /**
     * Background color of the story (ARGB)
     * @type {string}
     * @memberof SenderStoriesAudio
     */
    backgroundColor?: string;
}

/**
 * Check if a given object implements the SenderStoriesAudio interface.
 */
export function instanceOfSenderStoriesAudio(value: object): value is SenderStoriesAudio {
    if (!('media' in value) || value['media'] === undefined) return false;
    return true;
}

export function SenderStoriesAudioFromJSON(json: any): SenderStoriesAudio {
    return SenderStoriesAudioFromJSONTyped(json, false);
}

export function SenderStoriesAudioFromJSONTyped(json: any, ignoreDiscriminator: boolean): SenderStoriesAudio {
    if (json == null) {
        return json;
    }
    return {
        
        'media': SendMediaMediaFromJSON(json['media']),
        'mimeType': json['mime_type'] == null ? undefined : json['mime_type'],
        'noEncode': json['no_encode'] == null ? undefined : json['no_encode'],
        'noCache': json['no_cache'] == null ? undefined : json['no_cache'],
        'seconds': json['seconds'] == null ? undefined : json['seconds'],
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
        'contacts': json['contacts'] == null ? undefined : json['contacts'],
        'excludeContacts': json['exclude_contacts'] == null ? undefined : json['exclude_contacts'],
        'backgroundColor': json['background_color'] == null ? undefined : json['background_color'],
    };
}

export function SenderStoriesAudioToJSON(json: any): SenderStoriesAudio {
    return SenderStoriesAudioToJSONTyped(json, false);
}

export function SenderStoriesAudioToJSONTyped(value?: SenderStoriesAudio | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'media': SendMediaMediaToJSON(value['media']),
        'mime_type': value['mimeType'],
        'no_encode': value['noEncode'],
        'no_cache': value['noCache'],
        'seconds': value['seconds'],
        'width': value['width'],
        'height': value['height'],
        'contacts': value['contacts'],
        'exclude_contacts': value['excludeContacts'],
        'background_color': value['backgroundColor'],
    };
}

