/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SendMediaMedia } from './SendMediaMedia';
import {
    SendMediaMediaFromJSON,
    SendMediaMediaFromJSONTyped,
    SendMediaMediaToJSON,
    SendMediaMediaToJSONTyped,
} from './SendMediaMedia';

/**
 * 
 * @export
 * @interface SenderCatalogByID
 */
export interface SenderCatalogByID {
    /**
     * Use the phone number or [Chat ID](https://support.whapi.cloud/help-desk/faq/chat-id.-what-is-it-and-how-to-get-it) of the contact/group/channel to which you want to send the message. Use [Get groups](https://whapi.readme.io/reference/getgroups) to get the group ID.
     * @type {string}
     * @memberof SenderCatalogByID
     */
    to: string;
    /**
     * Message ID of the message to be quoted
     * @type {string}
     * @memberof SenderCatalogByID
     */
    quoted?: string;
    /**
     * Time in seconds for the message to be deleted. The Disappearing messages setting should be enabled in the chat where you are sending this message.
     * @type {number}
     * @memberof SenderCatalogByID
     */
    ephemeral?: number;
    /**
     * Message ID of the message to be edited
     * @type {string}
     * @memberof SenderCatalogByID
     */
    edit?: string;
    /**
     * 
     * @type {SendMediaMedia}
     * @memberof SenderCatalogByID
     */
    media?: SendMediaMedia;
    /**
     * Mime type of media
     * @type {string}
     * @memberof SenderCatalogByID
     */
    mimeType?: string;
    /**
     * Do not use our encoding
     * @type {boolean}
     * @memberof SenderCatalogByID
     */
    noEncode?: boolean;
    /**
     * Do not use the cache in a request
     * @type {boolean}
     * @memberof SenderCatalogByID
     */
    noCache?: boolean;
    /**
     * The numbers of the mentioned users
     * @type {Array<string>}
     * @memberof SenderCatalogByID
     */
    mentions?: Array<string>;
    /**
     * Is view once
     * @type {boolean}
     * @memberof SenderCatalogByID
     */
    viewOnce?: boolean;
    /**
     * Title of the catalog (if not set, the business name will be used)
     * @type {string}
     * @memberof SenderCatalogByID
     */
    title?: string;
    /**
     * Description of the catalog
     * @type {string}
     * @memberof SenderCatalogByID
     */
    description?: string;
    /**
     * Message text with link. Example: "Follow this link to view our catalog on WhatsApp". Use %URL% to insert the catalog link.
     * 
     * @type {string}
     * @memberof SenderCatalogByID
     */
    body?: string;
    /**
     * Type of the catalog preview. Use 'product' to set a first product image as preview,  'business_profile' to set the business profile pic as preview,  'thumbnail' to set a custom small jpeg image from 'preview' param as preview,  'media' to set a custom large image from 'media' param as large preview,  'style1' to set a isometric style for catalog preview stub, 'style2' to set a flat style for catalog preview stub, 'style3' to set a WA style for catalog preview stub, or 'none' to not set a preview. If not set, the default is product.
     * 
     * @type {string}
     * @memberof SenderCatalogByID
     */
    previewType?: SenderCatalogByIDPreviewTypeEnum;
    /**
     * Base64 encoded image for small version catalog preview (preview_type=thumbnail). In JPEG format
     * @type {string}
     * @memberof SenderCatalogByID
     */
    preview?: string;
}


/**
 * @export
 */
export const SenderCatalogByIDPreviewTypeEnum = {
    Product: 'product',
    BusinessProfile: 'business_profile',
    Thumbnail: 'thumbnail',
    Media: 'media',
    Style1: 'style1',
    Style2: 'style2',
    Style3: 'style3',
    None: 'none'
} as const;
export type SenderCatalogByIDPreviewTypeEnum = typeof SenderCatalogByIDPreviewTypeEnum[keyof typeof SenderCatalogByIDPreviewTypeEnum];


/**
 * Check if a given object implements the SenderCatalogByID interface.
 */
export function instanceOfSenderCatalogByID(value: object): value is SenderCatalogByID {
    if (!('to' in value) || value['to'] === undefined) return false;
    return true;
}

export function SenderCatalogByIDFromJSON(json: any): SenderCatalogByID {
    return SenderCatalogByIDFromJSONTyped(json, false);
}

export function SenderCatalogByIDFromJSONTyped(json: any, ignoreDiscriminator: boolean): SenderCatalogByID {
    if (json == null) {
        return json;
    }
    return {
        
        'to': json['to'],
        'quoted': json['quoted'] == null ? undefined : json['quoted'],
        'ephemeral': json['ephemeral'] == null ? undefined : json['ephemeral'],
        'edit': json['edit'] == null ? undefined : json['edit'],
        'media': json['media'] == null ? undefined : SendMediaMediaFromJSON(json['media']),
        'mimeType': json['mime_type'] == null ? undefined : json['mime_type'],
        'noEncode': json['no_encode'] == null ? undefined : json['no_encode'],
        'noCache': json['no_cache'] == null ? undefined : json['no_cache'],
        'mentions': json['mentions'] == null ? undefined : json['mentions'],
        'viewOnce': json['view_once'] == null ? undefined : json['view_once'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'body': json['body'] == null ? undefined : json['body'],
        'previewType': json['preview_type'] == null ? undefined : json['preview_type'],
        'preview': json['preview'] == null ? undefined : json['preview'],
    };
}

export function SenderCatalogByIDToJSON(json: any): SenderCatalogByID {
    return SenderCatalogByIDToJSONTyped(json, false);
}

export function SenderCatalogByIDToJSONTyped(value?: SenderCatalogByID | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'to': value['to'],
        'quoted': value['quoted'],
        'ephemeral': value['ephemeral'],
        'edit': value['edit'],
        'media': SendMediaMediaToJSON(value['media']),
        'mime_type': value['mimeType'],
        'no_encode': value['noEncode'],
        'no_cache': value['noCache'],
        'mentions': value['mentions'],
        'view_once': value['viewOnce'],
        'title': value['title'],
        'description': value['description'],
        'body': value['body'],
        'preview_type': value['previewType'],
        'preview': value['preview'],
    };
}

