/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SendMediaMedia } from './SendMediaMedia';
import {
    SendMediaMediaFromJSON,
    SendMediaMediaFromJSONTyped,
    SendMediaMediaToJSON,
    SendMediaMediaToJSONTyped,
} from './SendMediaMedia';

/**
 * 
 * @export
 * @interface SenderLinkPreview
 */
export interface SenderLinkPreview {
    /**
     * Use the phone number or [Chat ID](https://support.whapi.cloud/help-desk/faq/chat-id.-what-is-it-and-how-to-get-it) of the contact/group/channel to which you want to send the message. Use [Get groups](https://whapi.readme.io/reference/getgroups) to get the group ID.
     * @type {string}
     * @memberof SenderLinkPreview
     */
    to: string;
    /**
     * Message ID of the message to be quoted
     * @type {string}
     * @memberof SenderLinkPreview
     */
    quoted?: string;
    /**
     * Time in seconds for the message to be deleted. The Disappearing messages setting should be enabled in the chat where you are sending this message.
     * @type {number}
     * @memberof SenderLinkPreview
     */
    ephemeral?: number;
    /**
     * Message ID of the message to be edited
     * @type {string}
     * @memberof SenderLinkPreview
     */
    edit?: string;
    /**
     * Message text
     * @type {string}
     * @memberof SenderLinkPreview
     */
    body: string;
    /**
     * Title of the link
     * @type {string}
     * @memberof SenderLinkPreview
     */
    title: string;
    /**
     * Description of the link
     * @type {string}
     * @memberof SenderLinkPreview
     */
    description?: string;
    /**
     * Canonical URL of the link (for example, if the link is shortened)
     * @type {string}
     * @memberof SenderLinkPreview
     */
    canonical?: string;
    /**
     * Base64 encoded image for mini version link preview. In JPEG format
     * @type {string}
     * @memberof SenderLinkPreview
     */
    preview?: string;
    /**
     * 
     * @type {SendMediaMedia}
     * @memberof SenderLinkPreview
     */
    media?: SendMediaMedia;
    /**
     * Mime type of media
     * @type {string}
     * @memberof SenderLinkPreview
     */
    mimeType?: string;
    /**
     * Do not use our encoding
     * @type {boolean}
     * @memberof SenderLinkPreview
     */
    noEncode?: boolean;
    /**
     * Do not use the cache in a request
     * @type {boolean}
     * @memberof SenderLinkPreview
     */
    noCache?: boolean;
    /**
     * The numbers of the mentioned users
     * @type {Array<string>}
     * @memberof SenderLinkPreview
     */
    mentions?: Array<string>;
    /**
     * Is view once
     * @type {boolean}
     * @memberof SenderLinkPreview
     */
    viewOnce?: boolean;
}

/**
 * Check if a given object implements the SenderLinkPreview interface.
 */
export function instanceOfSenderLinkPreview(value: object): value is SenderLinkPreview {
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function SenderLinkPreviewFromJSON(json: any): SenderLinkPreview {
    return SenderLinkPreviewFromJSONTyped(json, false);
}

export function SenderLinkPreviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): SenderLinkPreview {
    if (json == null) {
        return json;
    }
    return {
        
        'to': json['to'],
        'quoted': json['quoted'] == null ? undefined : json['quoted'],
        'ephemeral': json['ephemeral'] == null ? undefined : json['ephemeral'],
        'edit': json['edit'] == null ? undefined : json['edit'],
        'body': json['body'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'canonical': json['canonical'] == null ? undefined : json['canonical'],
        'preview': json['preview'] == null ? undefined : json['preview'],
        'media': json['media'] == null ? undefined : SendMediaMediaFromJSON(json['media']),
        'mimeType': json['mime_type'] == null ? undefined : json['mime_type'],
        'noEncode': json['no_encode'] == null ? undefined : json['no_encode'],
        'noCache': json['no_cache'] == null ? undefined : json['no_cache'],
        'mentions': json['mentions'] == null ? undefined : json['mentions'],
        'viewOnce': json['view_once'] == null ? undefined : json['view_once'],
    };
}

export function SenderLinkPreviewToJSON(json: any): SenderLinkPreview {
    return SenderLinkPreviewToJSONTyped(json, false);
}

export function SenderLinkPreviewToJSONTyped(value?: SenderLinkPreview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'to': value['to'],
        'quoted': value['quoted'],
        'ephemeral': value['ephemeral'],
        'edit': value['edit'],
        'body': value['body'],
        'title': value['title'],
        'description': value['description'],
        'canonical': value['canonical'],
        'preview': value['preview'],
        'media': SendMediaMediaToJSON(value['media']),
        'mime_type': value['mimeType'],
        'no_encode': value['noEncode'],
        'no_cache': value['noCache'],
        'mentions': value['mentions'],
        'view_once': value['viewOnce'],
    };
}

