/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SendMediaMedia } from './SendMediaMedia';
import {
    SendMediaMediaFromJSON,
    SendMediaMediaFromJSONTyped,
    SendMediaMediaToJSON,
    SendMediaMediaToJSONTyped,
} from './SendMediaMedia';

/**
 * 
 * @export
 * @interface SenderSticker
 */
export interface SenderSticker {
    /**
     * Use the phone number or [Chat ID](https://support.whapi.cloud/help-desk/faq/chat-id.-what-is-it-and-how-to-get-it) of the contact/group/channel to which you want to send the message. Use [Get groups](https://whapi.readme.io/reference/getgroups) to get the group ID.
     * @type {string}
     * @memberof SenderSticker
     */
    to: string;
    /**
     * Message ID of the message to be quoted
     * @type {string}
     * @memberof SenderSticker
     */
    quoted?: string;
    /**
     * Time in seconds for the message to be deleted. The Disappearing messages setting should be enabled in the chat where you are sending this message.
     * @type {number}
     * @memberof SenderSticker
     */
    ephemeral?: number;
    /**
     * Message ID of the message to be edited
     * @type {string}
     * @memberof SenderSticker
     */
    edit?: string;
    /**
     * 
     * @type {SendMediaMedia}
     * @memberof SenderSticker
     */
    media: SendMediaMedia;
    /**
     * Mime type of media
     * @type {string}
     * @memberof SenderSticker
     */
    mimeType?: string;
    /**
     * Do not use our encoding
     * @type {boolean}
     * @memberof SenderSticker
     */
    noEncode?: boolean;
    /**
     * Do not use the cache in a request
     * @type {boolean}
     * @memberof SenderSticker
     */
    noCache?: boolean;
    /**
     * Optional. For stickers, this field indicates whether the sticker is animated.
     * @type {boolean}
     * @memberof SenderSticker
     */
    animated?: boolean;
    /**
     * Width of the media in pixels
     * @type {number}
     * @memberof SenderSticker
     */
    width?: number;
    /**
     * Height of the media in pixels
     * @type {number}
     * @memberof SenderSticker
     */
    height?: number;
    /**
     * Is view once
     * @type {boolean}
     * @memberof SenderSticker
     */
    viewOnce?: boolean;
}

/**
 * Check if a given object implements the SenderSticker interface.
 */
export function instanceOfSenderSticker(value: object): value is SenderSticker {
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('media' in value) || value['media'] === undefined) return false;
    return true;
}

export function SenderStickerFromJSON(json: any): SenderSticker {
    return SenderStickerFromJSONTyped(json, false);
}

export function SenderStickerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SenderSticker {
    if (json == null) {
        return json;
    }
    return {
        
        'to': json['to'],
        'quoted': json['quoted'] == null ? undefined : json['quoted'],
        'ephemeral': json['ephemeral'] == null ? undefined : json['ephemeral'],
        'edit': json['edit'] == null ? undefined : json['edit'],
        'media': SendMediaMediaFromJSON(json['media']),
        'mimeType': json['mime_type'] == null ? undefined : json['mime_type'],
        'noEncode': json['no_encode'] == null ? undefined : json['no_encode'],
        'noCache': json['no_cache'] == null ? undefined : json['no_cache'],
        'animated': json['animated'] == null ? undefined : json['animated'],
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
        'viewOnce': json['view_once'] == null ? undefined : json['view_once'],
    };
}

export function SenderStickerToJSON(json: any): SenderSticker {
    return SenderStickerToJSONTyped(json, false);
}

export function SenderStickerToJSONTyped(value?: SenderSticker | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'to': value['to'],
        'quoted': value['quoted'],
        'ephemeral': value['ephemeral'],
        'edit': value['edit'],
        'media': SendMediaMediaToJSON(value['media']),
        'mime_type': value['mimeType'],
        'no_encode': value['noEncode'],
        'no_cache': value['noCache'],
        'animated': value['animated'],
        'width': value['width'],
        'height': value['height'],
        'view_once': value['viewOnce'],
    };
}

