/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
    MessageToJSONTyped,
} from './Message';

/**
 * 
 * @export
 * @interface SentMessage
 */
export interface SentMessage {
    /**
     * Message sent
     * @type {boolean}
     * @memberof SentMessage
     */
    sent: boolean;
    /**
     * 
     * @type {Message}
     * @memberof SentMessage
     */
    message?: Message;
}

/**
 * Check if a given object implements the SentMessage interface.
 */
export function instanceOfSentMessage(value: object): value is SentMessage {
    if (!('sent' in value) || value['sent'] === undefined) return false;
    return true;
}

export function SentMessageFromJSON(json: any): SentMessage {
    return SentMessageFromJSONTyped(json, false);
}

export function SentMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SentMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'sent': json['sent'],
        'message': json['message'] == null ? undefined : MessageFromJSON(json['message']),
    };
}

export function SentMessageToJSON(json: any): SentMessage {
    return SentMessageToJSONTyped(json, false);
}

export function SentMessageToJSONTyped(value?: SentMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sent': value['sent'],
        'message': MessageToJSON(value['message']),
    };
}

