/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Status } from './Status';
import {
    StatusFromJSON,
    StatusFromJSONTyped,
    StatusToJSON,
    StatusToJSONTyped,
} from './Status';

/**
 * 
 * @export
 * @interface StatusesList
 */
export interface StatusesList {
    /**
     * 
     * @type {Array<Status>}
     * @memberof StatusesList
     */
    statuses?: Array<Status>;
}

/**
 * Check if a given object implements the StatusesList interface.
 */
export function instanceOfStatusesList(value: object): value is StatusesList {
    return true;
}

export function StatusesListFromJSON(json: any): StatusesList {
    return StatusesListFromJSONTyped(json, false);
}

export function StatusesListFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusesList {
    if (json == null) {
        return json;
    }
    return {
        
        'statuses': json['statuses'] == null ? undefined : ((json['statuses'] as Array<any>).map(StatusFromJSON)),
    };
}

export function StatusesListToJSON(json: any): StatusesList {
    return StatusesListToJSONTyped(json, false);
}

export function StatusesListToJSONTyped(value?: StatusesList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statuses': value['statuses'] == null ? undefined : ((value['statuses'] as Array<any>).map(StatusToJSON)),
    };
}

