/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadMedia
 */
export interface UploadMedia {
    /**
     * Media ID
     * @type {string}
     * @memberof UploadMedia
     */
    id?: string;
}

/**
 * Check if a given object implements the UploadMedia interface.
 */
export function instanceOfUploadMedia(value: object): value is UploadMedia {
    return true;
}

export function UploadMediaFromJSON(json: any): UploadMedia {
    return UploadMediaFromJSONTyped(json, false);
}

export function UploadMediaFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadMedia {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function UploadMediaToJSON(json: any): UploadMedia {
    return UploadMediaToJSONTyped(json, false);
}

export function UploadMediaToJSONTyped(value?: UploadMedia | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

