/* tslint:disable */
/* eslint-disable */
/**
 * Whapi API
 * Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: care@whapi.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProfileUpdate
 */
export interface UserProfileUpdate {
    /**
     * Update user name.
     * @type {string}
     * @memberof UserProfileUpdate
     */
    name?: string;
    /**
     * Update user info in About section.
     * @type {string}
     * @memberof UserProfileUpdate
     */
    about?: string;
    /**
     * Update user icon in base64/url.
     * @type {string}
     * @memberof UserProfileUpdate
     */
    icon?: string;
}

/**
 * Check if a given object implements the UserProfileUpdate interface.
 */
export function instanceOfUserProfileUpdate(value: object): value is UserProfileUpdate {
    return true;
}

export function UserProfileUpdateFromJSON(json: any): UserProfileUpdate {
    return UserProfileUpdateFromJSONTyped(json, false);
}

export function UserProfileUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'about': json['about'] == null ? undefined : json['about'],
        'icon': json['icon'] == null ? undefined : json['icon'],
    };
}

export function UserProfileUpdateToJSON(json: any): UserProfileUpdate {
    return UserProfileUpdateToJSONTyped(json, false);
}

export function UserProfileUpdateToJSONTyped(value?: UserProfileUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'about': value['about'],
        'icon': value['icon'],
    };
}

